version: '3.4'

services:

  discountshopdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4  

  rabbitmq:
    image: rabbitmq:3-management-alpine

  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: src/Services/Shop/Shop.API/Dockerfile
    depends_on:
      - discountshopdb

  discounting.api:
    image: ${DOCKER_REGISTRY-}discountingapi
    build:
      context: .
      dockerfile: src/Services/Discounting/Discounting.API/Dockerfile
    depends_on:
      - discountshopdb


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotAPIGateWay/Dockerfile

volumes:
  pgadmin-data:
  discountshop-database:

