version: '3.4'

services:

  discountshopdb:
    container_name: discountshopdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=postgres
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - discountshop-database:/var/lib/postgresql/data/


  pgadmin:
    container_name: pgadmin1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@discountshop.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin-data:/root/.pgadmin

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
     - "5672:5672"
     - "15672:15672"
  shopping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ShopConnectionString=Server=discountshopdb;Port=5432;Database=shopDb;UId=admin;Password=admin1234;
      - EventBus__EventBusConnection=rabbitmq
    ports:
      - "6010:80"

  discounting.api:
    container_name: discounting.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DiscountConnectionString=Server=discountshopdb;Port=5432;Database=discountDb;UId=admin;Password=admin1234;
      - EventBus__EventBusConnection=rabbitmq
    ports:
      - "6012:80"


  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discounting.api
    ports:
      - "8010:80"




